name: Auto Greening Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    # TAMBAHKAN BAGIAN INI UNTUK MEMBERI IZIN TULIS
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'imdypha-bot'
          git config --global user.email 'imdypha-bot@users.noreply.github.com'

      - name: Create Empty Commit
        run: |
          git commit --allow-empty -m "feat: Automatic daily commit for green graph"

      # UBAH LANGKAH PUSH MENJADI LEBIH SEDERHANA
      - name: Push changes
        run: git push
